<!-- Header Section -->
<?php
include("includes/templates/header.php");
?>

<!-- Main Content -->
<main>
    <div class="breadcrums">
        <nav>
            <i class="fa-solid fa-house"></i>&emsp;
            <a href="index.php">The Trust Model</a>&emsp;
            <i class="fa-solid fa-chevron-right"></i>&emsp;
            <a href="#">Guidelines</a>
        </nav>
        <div class="headline">
            <h1>Guidelines for you who want to create an AI</h1>
        </div>
        <div class="horizontal">

            <!--     Description of the stamp       -->
            <div class="guide_info">
                <h1 class="headline">The Stamp of Quality</h1>
                <div class="textTrustModel">
                    <p>The Stamp of Quality represents a mark of trust for AI systems used within the public sector. It shows that the AI has been carefully evaluated and meets important legal, ethical, and transparency standards. Receiving the stamp means that the AI system is in compliance with regulations and can be trusted to operate responsibly, without violating laws or compromising user rights. It also demonstrates that the organization behind the AI system has taken the necessary steps to ensure accountability and transparency in its use of AI technology.</p>
                    <p class="chatgpt">Generated by ChatGPT</p>
                </div>
            </div>

            <!--     Description of high risk       -->
            <div class="guide_info">
                <h1 class="headline">High Risk AI-Systems</h1>
                <div class="textTrustModel">
                    <p>A High Risk AI-System refers to AI applications that can significantly impact individuals or society, especially if they handle sensitive data or perform critical tasks. These systems may be used in areas like law enforcement, healthcare, education, or social services, where errors or misuse could have serious consequences. High risk means there is a greater potential for harm or violation of rights, so these systems are subject to stricter rules and regulations to ensure they are used safely and ethically.</p>
                    <p class="chatgpt">Generated by ChatGPT</p>
                </div>
            </div>

            <!--     Description of low risk        -->
            <div class="guide_info">
                <h1 class="headline">Low Risk AI-Systems</h1>
                <div class="textTrustModel">
                    <p>A Low Risk AI-System is one that poses minimal potential for harm or negative impact on individuals or society. These systems are usually used in less sensitive areas, where their outcomes are unlikely to cause significant disruption or risk to people’s rights and well-being. While they still need to follow legal guidelines, they face fewer regulatory restrictions compared to high-risk systems, due to the lower chance of causing harm.</p>
                    <p class="chatgpt">Generated by ChatGPT</p>
                </div>
            </div>

        </div>
    </div>
</main>

<!-- Footer Section -->
<?php
include("includes/templates/footer.php");
?>